### ISSUE TITLE
Authentication credentials were not provided

### ISSUE THREAD

**Issue by raymonvdm** [stfc/netbox-to-librenms#2]
I`m trying to understand this script but it fails on the authenticaton credentials wich are not provided in the config file

```
pynetbox.core.query.RequestError: The request failed with code 403 Forbidden: {'detail': 'Authentication credentials were not provided.'}
```

**Comment by rfdrake** [comment]
I thought at first it was something they removed when creating this public repo, but now I suspect they are running netbox with the default option which shows information to guests, so they didn't need an API key to read from netbox.

In order to fix this you would need to find this line

    nb = pynetbox.api('https://netbox.esc.rl.ac.uk')

and change it to this:

    nb = pynetbox.api(nb_url, token=nb_token)

Where nb_url is your netbox url and nb_token is your API token.

**Comment by drossy** [comment]
I've now updated the script to require the token, and removed some of our local configuration details from the script.
